export const blogList = [
  {
    id: 1,
    title: 'Jimmy',
    category: 'Puppy',
    subCategory: ['frontend', 'ui/ux', 'design'],
    description:
      "hhhhhhhhhhh.",
    authorName: 'Blue Cross Of India',
    authorAvatar: '/assets/images/author.jpg',
    createdAt: 'June 03, 2021',
    cover: '/assets/images/dog1.jpg',
  },
  {
    id: 2,
    title: 'Tom',
    category: 'puppy',
    subCategory: ['vacation', 'holidays', 'sight seeing'],
    description:
      "hhhhhhhhhhh.",
    authorName: 'Blue Cross Of India',
    authorAvatar: '/assets/images/author.jpg',
    createdAt: 'June 03, 2021',
    cover: '/assets/images/dog2.jpg',
  },
  {
    id: 3,
    title: 'JIMMY',
    category: 'Kitten',
    subCategory: ['e-commerce store', 'clothing', 'shopping store'],
    description:
      "hhhhhhhhhhh.",
    authorName: 'Blue Cross Of India',
    authorAvatar: '/assets/images/author.jpg',
    createdAt: 'June 03, 2021',
    cover: '/assets/images/kit1.jpg',
  },
  {
    id: 4,
    title: 'JIMMY',
    category: 'Puppy',
    subCategory: ['adrenaline', 'stay-fit', 'lifestyle'],
    description:
      "hhhhhhhhhhh.",
    // authorName: 'Blue Cross Of India',
    // authorAvatar: '/assets/images/author.jpg',
    // createdAt: 'June 03, 2021',
    cover: '/assets/images/dog3.jpg',
  },
  {
    id: 5,
    title: 'JIMMY',
    category: 'Kitten',
    subCategory: ['bbq', 'food', 'lifestyle'],
    description:
      "hhhhhhhhhhh.",
    authorName: 'Blue Cross Of India',
    authorAvatar: '/assets/images/author.jpg',
    createdAt: 'June 03, 2021',
    cover: '/assets/images/kit2.jpg',
  },
  {
    id: 6,
    title: 'JIMMY',
    category: 'puppy',
    subCategory: ['beaches', 'sea', 'holidays'],
    description:
      "hhhhhhhhhhh.",
    authorName: 'Blue Cross Of India',
    authorAvatar: '/assets/images/author.jpg',
    createdAt: 'June 03, 2021',
    cover:
      '/assets/images/dog4.jpg',
  },
  {
    id: 7,
    title: 'JIMMY',
    category: 'art',
    subCategory: ['skill', 'design', 'passion'],
    description:
      "hhhhhhhhhhh.",
    authorName: 'Blue Cross Of India',
    authorAvatar: '/assets/images/author.jpg',
    createdAt: 'June 03, 2021',
    cover: '/assets/images/kit3.jpg',
  },
  {
    id: 2,
    title: 'JIMMY',
    category: 'puppy',
    subCategory: ['vacation', 'holidays', 'sight seeing'],
    description:
      "hhhhhhhhhhh.",
    authorName: 'Blue Cross Of India',
    authorAvatar: '/assets/images/author.jpg',
    createdAt: 'June 03, 2021',
    cover: '/assets/images/puppy7.jpg',
  },
  {
    id: 2,
    title: 'JIMMY',
    category: 'puppy',
    subCategory: ['vacation', 'holidays', 'sight seeing'],
    description:
      "hhhhhhhhhhh.",
    authorName: 'Blue Cross Of India',
    authorAvatar: '/assets/images/author.jpg',
    createdAt: 'June 03, 2021',
    cover: '/assets/images/puppy6.jpg',
  },
  {
    id: 2,
    title: 'JIMMY',
    category: 'puppy',
    subCategory: ['vacation', 'holidays', 'sight seeing'],
    description:
      "hhhhhhhhhhh.",
    authorName: 'Blue Cross Of India',
    authorAvatar: '/assets/images/author.jpg',
    createdAt: 'June 03, 2021',
    cover: '/assets/images/puppy5.jpg',
  },
  {
    id: 2,
    title: 'JIMMY',
    category: 'puppy',
    subCategory: ['vacation', 'holidays', 'sight seeing'],
    description:
      "hhhhhhhhhhh.",
    authorName: 'Blue Cross Of India',
    authorAvatar: '/assets/images/author.jpg',
    createdAt: 'June 03, 2021',
    cover: '/assets/images/puppy4.jpg',
  },
  {
    id: 2,
    title: 'JIMMY',
    category: 'puppy',
    subCategory: ['vacation', 'holidays', 'sight seeing'],
    description:
      "hhhhhhhhhhh.",
    authorName: 'Blue Cross Of India',
    authorAvatar: '/assets/images/author.jpg',
    createdAt: 'June 03, 2021',
    cover: '/assets/images/puppy3.jpg',
  },
  {
    id: 2,
    title: 'JIMMY',
    category: 'puppy',
    subCategory: ['vacation', 'holidays', 'sight seeing'],
    description:
      "hhhhhhhhhhh.",
    authorName: 'Blue Cross Of India',
    authorAvatar: '/assets/images/author.jpg',
    createdAt: 'June 03, 2021',
    cover: '/assets/images/puppy2.jpg',
  },
  {
    id: 2,
    title: 'JIMMY',
    category: 'puppy',
    subCategory: ['vacation', 'holidays', 'sight seeing'],
    description:
      "hhhhhhhhhhh.",
    authorName: 'Blue Cross Of India',
    authorAvatar: '/assets/images/author.jpg',
    createdAt: 'June 03, 2021',
    cover: '/assets/images/dog4.jpg',
  },
  {
    id: 2,
    title: 'JIMMY',
    category: 'puppy',
    subCategory: ['vacation', 'holidays', 'sight seeing'],
    description:
      "hhhhhhhhhhh.",
    authorName: 'Blue Cross Of India',
    authorAvatar: '/assets/images/author.jpg',
    createdAt: 'June 03, 2021',
    cover: '/assets/images/kit3.jpg',
  },
  {
    id: 2,
    title: 'JIMMY',
    category: 'puppy',
    subCategory: ['vacation', 'holidays', 'sight seeing'],
    description:
      "hhhhhhhhhhh.",
    authorName: 'Blue Cross Of India',
    authorAvatar: '/assets/images/author.jpg',
    createdAt: 'June 03, 2021',
    cover: '/assets/images/dog5.jpg',
  },
  {
    id: 2,
    title: 'JIMMY',
    category: 'puppy',
    subCategory: ['vacation', 'holidays', 'sight seeing'],
    description:
      "hhhhhhhhhhh.",
    authorName: 'Blue Cross Of India',
    authorAvatar: '/assets/images/author.jpg',
    createdAt: 'June 03, 2021',
    cover: '/assets/images/kit4.jpg',
  },
  {
    id: 2,
    title: 'JIMMY',
    category: 'puppy',
    subCategory: ['vacation', 'holidays', 'sight seeing'],
    description:
      "hhhhhhhhhhh.",
    authorName: 'Blue Cross Of India',
    authorAvatar: '/assets/images/author.jpg',
    createdAt: 'June 03, 2021',
    cover: '/assets/images/dog6.jpg',
  },
  {
    id: 2,
    title: 'JIMMY',
    category: 'puppy',
    subCategory: ['vacation', 'holidays', 'sight seeing'],
    description:
      "hhhhhhhhhhh.",
    authorName: 'Blue Cross Of India',
    authorAvatar: '/assets/images/author.jpg',
    createdAt: 'June 03, 2021',
    cover: '/assets/images/kit5.jpg',
  },
  {
    id: 2,
    title: 'JIMMY',
    category: 'puppy',
    subCategory: ['vacation', 'holidays', 'sight seeing'],
    description:
      "hhhhhhhhhhh.",
    authorName: 'Blue Cross Of India',
    authorAvatar: '/assets/images/author.jpg',
    createdAt: 'June 03, 2021',
    cover: '/assets/images/dog7.jpg',
  },
  {
    id: 2,
    title: 'JIMMY',
    category: 'puppy',
    subCategory: ['vacation', 'holidays', 'sight seeing'],
    description:
      "hhhhhhhhhhh.",
    authorName: 'Blue Cross Of India',
    authorAvatar: '/assets/images/author.jpg',
    createdAt: 'June 03, 2021',
    cover: '/assets/images/kit6.jpg',
  },
  {
    id: 2,
    title: 'JIMMY',
    category: 'puppy',
    subCategory: ['vacation', 'holidays', 'sight seeing'],
    description:
      "hhhhhhhhhhh.",
    authorName: 'Blue Cross Of India',
    authorAvatar: '/assets/images/author.jpg',
    createdAt: 'June 03, 2021',
    cover: '/assets/images/dog8.jpg',
  },
  {
    id: 2,
    title: 'JIMMY',
    category: 'puppy',
    subCategory: ['vacation', 'holidays', 'sight seeing'],
    description:
      "hhhhhhhhhhh.",
    authorName: 'Blue Cross Of India',
    authorAvatar: '/assets/images/author.jpg',
    createdAt: 'June 03, 2021',
    cover: '/assets/images/kit7.jpg',
  },
  {
    id: 2,
    title: 'JIMMY',
    category: 'puppy',
    subCategory: ['vacation', 'holidays', 'sight seeing'],
    description:
      "hhhhhhhhhhh.",
    authorName: 'Blue Cross Of India',
    authorAvatar: '/assets/images/author.jpg',
    createdAt: 'June 03, 2021',
    cover: '/assets/images/kit8.jpg',
  },
  {
    id: 2,
    title: 'JIMMY',
    category: 'puppy',
    subCategory: ['vacation', 'holidays', 'sight seeing'],
    description:
      "hhhhhhhhhhh.",
    authorName: 'Blue Cross Of India',
    authorAvatar: '/assets/images/author.jpg',
    createdAt: 'June 03, 2021',
    cover: '/assets/images/kit9.jpg',
  },
  {
    id: 2,
    title: 'JIMMY',
    category: 'puppy',
    subCategory: ['vacation', 'holidays', 'sight seeing'],
    description:
      "hhhhhhhhhhh.",
    authorName: 'Blue Cross Of India',
    authorAvatar: '/assets/images/author.jpg',
    createdAt: 'June 03, 2021',
    cover: '/assets/images/kit10.jpg',
  },
  {
    id: 2,
    title: 'JIMMY',
    category: 'puppy',
    subCategory: ['vacation', 'holidays', 'sight seeing'],
    description:
      "hhhhhhhhhhh.",
    authorName: 'Blue Cross Of India',
    authorAvatar: '/assets/images/author.jpg',
    createdAt: 'June 03, 2021',
    cover: '/assets/images/puppy1',
  },
];
